### ISSUE TITLE
HAZPANES-Documentar Rosca de reyes -#23

### ISSUE THREAD

**Issue by amigospanarras** [mapadepanesvenezolanos/mapadepanesvenezolanos.github.io#105]
- [x] Documentar receta en google sheet
- [x] Preparar pan
- [x] Publicar receta en pagina web 
- [x] Preparar pan para fotos
- [x] Tomar fotos del paso a paso (10/01/2025)
- [x] Tomar fotos del pan horneado
- [x] Completar edicion de fotos
- [x] Integrar receta y fotos en documento maestro
- [x] generar version pdf
- [x] publicar version pdf. leanpub
- [x] notificar lectores de la nueva actualización del libro (#23) via leanpub
- [x] notificar lectores de la nueva actualización del libro (#23) via grupo whatsapp
- [ ] Integrar fotos paso a paso en documento maestro
- [ ] generar version pdf
- [ ] publicar version pdf. leanpub
- [ ] notificar lectores de la nueva actualización del libro (#24) via leanpub
- [ ] notificar lectores de la nueva actualización del libro (#24) via grupo whatsapp
